df <- data.frame(
  variable = c(
    "pid",
    "institution",
    "last_name",
    "first_name",
    "date_birth",
    "gender",
    "street",
    "house_nr",
    "post_code",
    "city",
    "country",
    "phone_number",
    "email",
    "insurance_name",
    "insurance_class",
    "insurance_number",
    "ahv",
    "consent",
    "gp_name",
    "gp_email",
    "referral_diagnosis",
    "anatomic_region",
    "anatomic_side",
    "clinical_history",
    "ecog_initial",
    "last_contact_date",
    "last_status",
    "death_date",
    "death_reason",
    "followup_physician"
  ),
  label = c(
    "Patient identifier",
    "Main institution",
    "Patient's last name",
    "Patient's first name",
    "Patient's date of birth",
    "Patient's gender",
    "Patient's address: street",
    "Patient's address: house number",
    "Patient's address: post code",
    "Patient's address: city",
    "Patient's address: country",
    "Patient's phone number",
    "Patient's email address",
    "Patient's insurance company",
    "Patient's insurance class",
    "Patient's insurance number",
    "Patient's AHV number",
    "Did patient give consent?",
    "Name of the patient's general practitioner",
    "Email address of the patient's general practitioner",
    "Referral diagnosis",
    "Anatomic region of tumor",
    "Anatomic side of tumor",
    "Patient's clinical history related to the tumor",
    "Initial ECOG performance status",
    "Date of the last patient contact",
    "Status at last patient contact",
    "Date of patient's death",
    "Reason fo patient's death",
    "Physician who conducted follow-up"
  ),
  explanation = 
    c("Used to identify each patient in the database, supplied by data contributor",
      "Main institution at which the patient is diagnosed and treated",
      "Patient's last name",
      "Patient's first name",
      "Patient's date of birth [yyyy-mm-dd]",
      "Patient's gender [2 levels: Male, Female]",
      "Patient's address: street",
      "Patient's address: house number",
      "Patient's address: post code",
      "Patient's address: city",
      "Patient's address: country",
      "Patient's phone number, starting with +[country_code]",
      "Patient's email address",
      "Patient's insurance company, has to be one from table insurance (variable name: insurance_name)",
      "Patient's insurance class [4 levels: general, half-private, private, self-paying]",
      "Patient's insurance number",
      "Patient's AHV number (serves as distinct identifier)",
      "Logical (TRUE, FALSE) that indicates if patient gave consent to be taken up into the SSN database",
      "Name of the patient's general practitioner",
      "Email address of the patient's general practitioner",
      "Referral diagnosis",
      "Anatomic region at which the tumor is located, has to be one from table anatomic_region (variable_name: anatomic_region_name)",
      "Anatomic side at which the tumor is located, [3 levels: Right, Left, Midline]",
      "Patient's clinical history related to the tumor",
      "Initial ECOG performance status (automatically calculated from PROM or manually filled in)",
      "Date of the last patient contact, used for time-to-event analysis",
      "Status of the patient at last patient contact, [5 levels: No evidence of disease (NED), Alive with disease (AWD), Dead of disease (DOD), Dead of other reason (DOR), Not applicable because no Sarcoma]",
      "Date of patient's death, supplied if last_status is ‘Dead of disease (DOD)‘ or ‘Dead of other reason (DOR)‘",
      "Reason of patient's death, [4 levels: Of other cancer, Of treatment complication, Of medical reason independent from cancer, Unknown]",
      "Name of the physician who conducted the follow-up"
      ),
  shiny_inputId = c(
    "personal_pid_new",
    "personal_institution",
    "personal_last_name",
    "personal_first_name",
    "personal_date_birth",
    "personal_gender",
    "personal_street",
    "personal_house_nr",
    "personal_post_code",
    "personal_city",
    "personal_country",
    "personal_phone_number",
    "personal_email",
    "personal_insurance_name",
    "personal_insurance_class",
    "personal_insurance_number",
    "personal_ahv",
    "personal_consent",
    "personal_gp_name",
    "personal_gp_email",
    "clinical_referral_diagnosis",
    "clinical_anatomic_region",
    "clinical_anatomic_side",
    "clinical_history",
    "clinical_ecog",
    "clinical_last_contact_date",
    "clinical_last_status",
    "clinical_death_date",
    "clinical_death_reason",
    "clinical_followup_physician"
  ),
  shiny_label = c(
    "PID for new patient",
    "Institution",
    "Last name",
    "First name",
    "Date of birth",
    "Gender",
    "Address: Street",
    "House number",
    "Post code",
    "City",
    "Country",
    "Phone number (incl. country code)",
    "E-Mail address",
    "Insurance company",
    "Insurance class",
    "Insurance number",
    "AHV number",
    "Did the patient give informed consent?",
    "Name of general practitioner",
    "E-Mail address of general practitioner",
    "Main referral diagnosis",
    "anatomic region",
    "Anatomic side of lesion",
    "Patient history (clinics, therapy up to now...)",
    "ECOG at diagnosis",
    "Date of last patient contact",
    "Status at last patient contact",
    "Date of death",
    "Reason of death",
    "Who conducted the follow-up?"
  )
)

