amputation_name <- data.frame(
  group = c("Not applicable",
            rep("forequarter", 2),
            rep("upper extremity", 6),
            rep("lower extremity", 6)),
  amputation_name = c("Not applicable",
                      "resB.52 forequarter amputation with chest wall",
                      "resB.53 forequarter amputation without chest wall",
                      # "resB.54 hemipelvectomy type V - 1. trans-acetabular (with dissociation of pelvic ring; excluding hip disarticulation)",
                      # "resB.55 hemipelvectomy type V - 2. trans-ilium (extra-articular - incl. supra-acetabular)",
                      # "resB.56 hemipelvectomy type V - 3. trans-hemi-sacral incl. hemilumbar without contralateral spinopelvic dissociation",
                      # "resB.57 hemipelvectomy type V - 4. trans-hemi-sacral incl. hemilumbar with contralateral spinopelvic dissociation",
                      # "resB.58 hemipelvectomy type V - 5. hemicorporectomy",
                      # "resB.59 * A: posterior flap",
                      # "resB.60 * B: anterior flap",
                      # "resB.61 * C: other (please specify in next field)",
                      "resB.62 shoulder joint trans-articular",
                      "resB.63 humerus",
                      "resB.64 elbow joint",
                      "resB.65 forearm",
                      "resB.66 hand / wrist",
                      "resB.67 finger",
                      "resB.68 hip disarticulation",
                      "resB.69 thigh",
                      "resB.70 knee joint",
                      "resB.71 BKA",
                      "resB.72 foot",
                      "resB.90 digit")
)

anatomic_region <- data.frame(
  group = c(
    "Not (yet) determined",
    rep("bone", 88),
    rep("superficial soft-tissue", 55),
    rep("deep soft-tissue", 119)
  ),
  region = c( "Not (yet) determined",
              rep("face/head/neck", 4),
              rep("upper extremity", 39),
              rep("torso (incl. chest, excl. sacrum)", 6),
              rep("pelvis (incl. sacrum)", 7),
              rep("lower extremity", 32),
              rep("face/head/neck", 5),
              rep("upper extremity", 19),
              rep("torso (incl. chest, excl. sacrum)", 4),
              rep("pelvis (incl. sacrum)", 4),
              rep("lower extremity", 18),
              rep("abdomen", 3),
              rep("chest (incl. mamma)", 2),
              rep("face/head/neck", 4),
              rep("upper extremity", 42),
              rep("torso, paravertebral (incl. spine)", 5),
              rep("pelvis", 11),
              rep("lower extremity", 44),
              rep("abdomen", 4),
              rep("chest (subfascial masses, excl. mamma", 9)
  ),
  sub = c("Not (yet) determined",
          rep("face/head/neck", 4),
          rep("clavicle", 3),
          rep("scapula", 5),
          rep("humerus", 7),
          rep("elbow joint", 2),
          rep("radius", 7),
          rep("ulna", 7),
          rep("radius & ulna", 2),
          rep("wrist joint", 2),
          rep("hand", 4),
          rep("torso (incl. chest, excl. sacrum)", 6),
          rep("pelvis (incl. sacrum)", 7),
          rep("femur", 7),
          rep("knee joint", 3),
          rep("tibia", 6),
          rep("fibula", 7),
          rep("tibia & fibula combinations", 2),
          rep("ankle joint", 3),
          rep("foot", 4),
          rep("face/head/neck", 5),
          rep("clavicle", 3),
          rep("scapula", 5),
          rep("upper arm / humerus", 3),
          rep("elbow joint", 2),
          rep("forearm", 3),
          rep("hand / wrist", 3),
          rep("torso (incl. chest, excl. sacrum)", 4),
          rep("pelvis (incl. sacrum)", 4),
          rep("thigh / femur", 9),
          rep("knee joint", 2),
          rep("lower leg", 2),
          rep("foot", 5),
          rep("abdomen", 3),
          rep("chest (incl. mamma)", 2),
          rep("face/head/neck", 4),
          rep("clavicle / brachial plexus", 2),
          rep("scapula / axilla / shoulder", 6),
          rep("shoulder joint", 2),
          rep("upper arm / humerus", 12),
          rep("elbow joint", 2),
          rep("forearm", 12),
          rep("wrist joint", 2),
          rep("hand", 4),
          rep("torso, paravertebral (incl. spine)", 5),
          rep("extrapelvic", 3),
          rep("intrapelvic (retroperitoneal)", 4),
          rep("both intra- and extrapelvic", 4),
          rep("hip joint", 2),
          rep("thigh / femur", 16),
          rep("knee joint", 4),
          rep("lower leg", 16),
          rep("ankle joint", 2),
          rep("foot", 4),
          rep("abdominal wall", 2),
          rep("intraabdominal", 2),
          rep("chest wall", 4),
          rep("intrathoracic", 5)
  ),
  anatomic_region_name = c(
    "Not (yet) determined",
    "B1 face, head, neck",
    "B1.1 face",
    "B1.2 head",
    "B1.3 neck",
    "B2 clavicle",
    "B2.1 medial clavicle",
    "B2.2 lateral clavicle",
    "B3.1.A partial intraarticular scapula",
    "B3.1.B partial extraarticular scapula",
    "B3.2.A complete intraarticular scapula",
    "B3.2.B complete extraarticular scapula",
    "B3.3 acromion (from base of scapular spine to AC-joint)",
    "B4.1. intraarticular proximal humerus",
    "B4.2. extraarticular proximal humerus",
    "B4.3. diaphyeal humerus",
    "B4.4. intraarticular distal humerus",
    "B4.5. extraarticular distal humerus",
    "B4.6. intraarticular humerus combinations",
    "B4.7. extraarticular humerus combinations",
    "B5.1. intraarticular elbow joint",
    "B5.2. extraarticular elbow joint",
    "B6.1. intraarticular radius proximal",
    "B6.2. extraarticular radius proximal",
    "B6.3. radius diaphyseal",
    "B6.4. intraarticular radius distal",
    "B6.5. extraarticular radius distal",
    "B6.6. intraarticular radius combinations",
    "B6.7. extraarticular radius combinations",
    "B6.8. intraarticular ulna proximal",
    "B6.9. extraarticular ulna proximal",
    "B6.10. ulna diaphyseal",
    "B6.11. intraarticular ulna distal",
    "B6.12. extraarticular ulna distal",
    "B6.13. intraarticular ulna combinations",
    "B6.14. extraarticular ulna combinations",
    "B6.15. intraarticular radius and ulna combinations",
    "B6.16. extraarticular radius and ulna combinations",
    "B7.1. intraarticular wrist joint",
    "B7.2. extraatricular wrist joint",
    "B8.1. carpal",
    "B8.2. matecarpal",
    "B8.3. digits",
    "B8.4. hand combinations",
    "B9.1. cervical spine",
    "B.9.2. thoracic spine",
    "B.9.3. lumbar spine",
    "B.9.5. ribs",
    "B.9.6. torso combinations",
    "B.9.7. sternum",
    "B10.1. ilium",
    "B10.2. ischium",
    "B10.3. pubis",
    "B10.4. pelvis combinations",
    "B10.5. acetabulum / hip joint: intraarticular",
    "B10.6. acetabulum / hip joint: extraatricular",
    "B10.7. sarcum",
    "B12.1. intraarticular proximal femur",
    "B12.2. extraarticular proximal femur",
    "B12.3. diaphyseal femur",
    "B12.4. intraarticular distal femur",
    "B12.5. extraatricular distal femur",
    "B12.6. intraarticular femur combinations",
    "B12.7. extraarticular femur combinations",
    "B13.1. patella intraarticular",
    "B13.2. patella extraatricular",
    "B13.3. combinations of patella intraartiuclar and patella extraatricular",
    "B14.1. intraarticular tibia proximal",
    "B14.2. extraatricular tibia proximal",
    "B14.3. tibia diaphyeal",
    "B14.4. intraarticular tibia distal",
    "B14.5. extraatricular tibia distal",
    "B14.6. tibia combinations",
    "B14.7. intraarticular fibula proximal",
    "B14.8. extraarticular fibula proximal",
    "B14.9. fibula diaphyseal",
    "B14.10. intraarticular fibula distal",
    "B14.11. extraatricular fibula distal",
    "B14.12. intraarticular fibula combinations",
    "B14.13. extraatricular fibula combinations",
    "B14.14. intraarticular tibia and fibula combinations",
    "B14.15. extraatricular tibia and fibula combinations",
    "B15.1. intraarticular ankle joint",
    "B15.2. extraarticular ankle joint",
    "B15.2.1. combinations of intraarticular ankle joint and extraarticular ankle joint",
    "B16.1. hindfoot",
    "B16.2. forefoot",
    "B16.3. digits",
    "B16.4. foot combinations",
    "S1 face",
    "S2 head",
    "S3 anterior neck",
    "S4 posterior neck",
    "S4.4 combinations of face, head, neck",
    "S7 clavicle region",
    "S7.1. medial clavicle",
    "S7.2. lateral clavicle",
    "S3.1. regio subscapularis",
    "S3.2. regio scapularis",
    "S3.3. regio infrascapularis",
    "S3.4. regio deltoidea",
    "S3.5. regio axillaris",
    "S4.1. regio brachialis anterior",
    "S4.2. regio brachialis posterior",
    "S4.3. combinations of regio brachialis anterior and regio brachialis posterior",
    "S5.1. regio cubitalis anterior",
    "S5.2. regio cubitalis posterior",
    "S6.1. regio antebrachii anterior",
    "S6.2. regio antebrachii posterior",
    "S6.3. combinations of regio antebrachii anterior and regio antebrachii posterior",
    "S8.1. dorsum manus",
    "S8.2. palma manus",
    "S8.3. digits",
    "S9.1. regio thoracalis",
    "S9.2. regio lumbalis",
    "S9.3. regio sacralis",
    "S9.4. regio analis",
    "S10.1. regio glutealis",
    "S10.2. regio pubica",
    "S10.3. regio urogenitalis / perinealis / analis",
    "S11.1. regio inguinalis",
    "S12.1. regio femoris anterior proximal",
    "S12.3. regio femoris anterior diaphyseal",
    "S12.5. regio femoris anterior distal",
    "S12.2. regio femoris posterior proximal",
    "S12.4. regio femoris posterior diaphyseal",
    "S12.6. regio femoris posterior distal",
    "S12.2.1. combinations of regio femoris anterior proximal and regio femoris posterior proximal",
    "S12.4.1. combinations of regio femoris anterior diaphyseal and regio femoris posterior diaphyseal",
    "S12.7. distal femur combinations",
    "S13.1. regio genus anterior",
    "S13.2. regio genus posterior",
    "S14.1. regio cruralis anterior",
    "S14.2. regio cruralis posterior",
    "S15.1. regio calcanea",
    "S16.1. dorsum pedis",
    "S16.2. planta pedis",
    "S16.3. digits",
    "S16.4. foot combinations",
    "S17.1. regio hypochondrica",
    "S17.2. regio umbilicalis",
    "S17.3. regio abdominalis lateralis",
    "S18.1. regio presternalis",
    "S18.2. regio pectoralis / mamma",
    "D1 face",
    "D2 head",
    "D3 anterior neck",
    "D4 posterior neck",
    "D2.1. clavicle",
    "D2.2. brachial plexus",
    "D3.1. deltoid region",
    "D3.2. superior shoulder",
    "D3.3. dorsal to scapula",
    "D3.4. inferior to scapula",
    "D3.5. axilla (base / lateral)",
    "D3.6. axilla-scapulo-thoracic-chest-wall (medial / deep)",
    "D17.1. intraarticular shoulder joint",
    "D17.2. extraarticular shoulder joint",
    "D4.1.1 anterior / flexor compartment: proximal",
    "D4.1.2 anterior / flexor compartment: diaphyseal",
    "D4.1.3 anterior / flexor compartment: distal",
    "D4.1.4 anterior / flexor compartment: combinations",
    "D4.2.1 posterior / extensor compartment: proximal",
    "D4.2.2 posterior / extensor compartment: diaphyseal",
    "D4.2.3 posterior / extensor compartment: distal",
    "D4.2.4 posterior / extensor compartment: combinations",
    "D4.3.1 compartment combinations: proximal",
    "D4.3.2 compartment combinations: diaphyseal",
    "D4.3.3 compartment combinations: distal",
    "D4.3.4 compartment combinations: combinations",
    "D5.1. intraarticular elbow joint",
    "D5.2. extraarticular elbow joint",
    "D6.1.1 anterior / flexor compartment: proximal",
    "D6.1.2 anterior / flexor compartment: diaphyseal",
    "D6.1.3 anterior / flexor compartment: distal",
    "D6.1.4 anterior / flexor compartment: combinations",
    "D6.2.1 posterior / extensor compartment: proximal",
    "D6.2.2 posterior / extensor compartment: diaphyseal",
    "D6.2.3 posterior / extensor compartment: distal",
    "D6.2.4 posterior / extensor compartment: combinations",
    "D6.3.1 compartment combinations: proximal",
    "D6.3.2 compartment combinations: diaphyseal",
    "D6.3.3 compartment combinations: distal",
    "D6.3.4 compartment combinations: combinations",
    "D7.1. intraarticular wrist joint",
    "D7.2. extraarticular wrist joint",
    "D8.1. dorsum manus",
    "D8.2. palma manus",
    "D8.3. hand combinations",
    "D8.4. fingers",
    "D9.1. cervical spine",
    "D9.2. thoracic spine / para-scapular region",
    "D9.3. lumbar spune / lumbar region",
    "D9.4. sacrum",
    "D9.5. combinations (incl. ilium)",
    "D10.3. abductors / gluteal muscles",
    "D11.1. inguina soft tissues (incl. funiculus spermaticus & scrotum)",
    "D10.4. extrapelvic, other (please specify in next field)",
    "D10.1. iliacus - psoas",
    "D10.1.1. uterus",
    "D10.2. intrapelvic, other (please specify in next field)",
    "D10.2.2. pararectal",
    "D10.6.1. anterior through inguina",
    "D10.6.4. anterior through foramen obturatum",
    "D10.6.2. lateral through sciatic notch",
    "D10.6.3. both intra- and extrapelvic, other (please specify in next field)",
    "D10.1. intraarticular hip joint",
    "D10.2. extraarticular hip joint",
    "D12.6.1 anterior / extensor compartment: proximal",
    "D12.6.2 anterior / extensor compartment: diaphyseal",
    "D12.6.3 anterior / extensor compartment: distal",
    "D12.6.4 anterior / extensor compartment: combinations",
    "D12.7.1 posterior / flexor compartment: proximal",
    "D12.7.2 posterior / flexor compartment: diaphyseal",
    "D12.7.3 posterior / flexor compartment: distal",
    "D12.7.4 posterior / flexor compartment: combinations",
    "D12.5.1 medial / adductor compartment: proximal",
    "D12.5.2 medial / adductor compartment: diaphyseal",
    "D12.5.3 medial / adductor compartment: distal",
    "D12.5.4 medial / adductor compartment: combinations",
    "D12.8.1 compartment combinations: anterior - posterior",
    "D12.8.2 compartment combinations: anterior - medial",
    "D12.8.3 compartment combinations: medial - posterior",
    "D12.8.4 compartment combinations: anterior - medial - posterior",
    "D13.1. periarticular, intraarticular knee joint",
    "D13.2. periarticular, extraarticular knee joint",
    "D13.3. popliteal, intraarticular knee joint",
    "D13.4. popliteal, extraarticular knee joint",
    "D14.2.1 anterior / extensor compartment: proximal",
    "D14.2.2 anterior / extensor compartment: diaphyseal",
    "D14.2.3 anterior / extensor compartment: distal",
    "D14.2.4 anterior / extensor compartment: combinations",
    "D14.3.1 posterior / flexor compartment: proximal",
    "D14.3.2 posterior / flexor compartment: diaphyseal",
    "D14.3.3 posterior / flexor compartment: distal",
    "D14.3.4 posterior / flexor compartment: combinations",
    "D14.1.1 lateral / fibular compartment: proximal",
    "D14.1.2 lateral / fibular compartment: diaphyseal",
    "D14.1.3 lateral / fibular compartment: distal",
    "D14.1.4 lateral / fibular compartment: combinations",
    "D14.4.1 compartment combinations: anterior - posterior",
    "D14.4.2 compartment combinations: anterior - fibular",
    "D14.4.3 compartment combinations: fibular - posterior",
    "D14.4.4 compartment combinations: anterior - fibular - posterior",
    "D15.1. intraarticular ankle joint",
    "D15.2. extraarticular ankle joint",
    "D16.1. dorsum pedis",
    "D16.2. planta pedis",
    "D16.4. digits",
    "D16.3. foot combinations",
    "D18.1. abdominal wall: anterior",
    "D18.2. abdominal wall: lateral",
    "D18.3. intraperitoneal",
    "D18.4. retro- / extraperitoneal",
    "D19.1. chest: sternal sternal",
    "D19.2. chest: pectoral pectoral",
    "D19.3. chest: lateral",
    "D19.3.1. chest: posterior",
    "D19.4.1. lung",
    "D19.4.2. pleura",
    "D19.4.3. mediastinum",
    "D19.4.4. heart",
    "D19.4.5. intrathoracic, other (please specify in next field)"
  )
)



diagnosis_who <- data.frame(
  group = c(
    "Not yet established",
    rep("soft tissue", 124),
    rep("bone", 52),
    rep("tumor syndromes", 11),
    rep("non-neoplastic / tumor simulator", 1),
    rep("metastasis", 13),
    rep("lymphoma / myeloma / leukemia", 3),
    rep("sequelae of treatment", 7)
  ),
  subgroup = c( "Not yet established",
                ### soft tissue
                rep("adipocytic tumors", 16),
                rep("fibroblastic / myofibroblastic tumors", 37),
                rep("so called fibrohistiocytic tumors", 4),
                rep("smooth muscle tumors", 2),
                rep("pericytic (perivascular) tumors", 3),
                rep("skeletal muscle tumors", 5),
                rep("vascular tumors of soft tissue", 12),
                rep("condro-osseous tumors", 4),
                rep("nerve sheath tumor", 16),
                rep("tumors of uncertain differentiation", 23),
                rep("undifferentiated / unclassified sarcoma", 2),
                ### bone
                rep("chondrogenic tumors", 13),
                rep("osteogenic tumors", 11),
                rep("fibrogenic tumors", 2),
                rep("fibrohistiocytic tumors", 2),
                rep("ewing sarcoma", 1),
                rep("osteoclastic giant cell rich tumors", 3),
                rep("notochodral tumors", 2),
                rep("vascular tumors", 4),
                rep("myogenic, lipogenic & epithelial tumors", 5),
                rep("tumors of undefined neoplastic nature", 8),
                rep("undifferentiated high-grade pleomorphic sarcoma", 1),
                ### tumor syndromes
                rep("tumor syndromes", 11),
                ### non-neoplastic / tumor simulator
                rep("non-neoplastic / tumor simulator", 1),
                ### metastasis
                rep("metastasis", 13),
                ### lymphoma / myeloma / leukemia
                rep("lymphoma / myeloma / leukemia", 3),
                ### sequelae of treatment
                rep("St. post implantation of tumor prosthesis", 6),
                rep("other sequelae of treatment", 1)
  ),
  diagnosis_name = c(
    "99 not yet established",
    ### adipocytic tumors
    "2.1.1. lipoma",
    "2.1.2. lipomatosis",
    "2.1.3. lipomatosis of nerve",
    "2.1.4. lipoblastoma / lipoblastomatosis",
    "2.1.5. angiolipoma",
    "2.1.6. myolipoma",
    "2.1.7. chondroid lipoma",
    "2.1.8. extra-renal angiomyolipoma",
    "2.1.9. extra‐adrenal myelolipoma",
    "2.1.10. spindle cell / pleomorphic lipoma",
    "2.1.11. hibernoma",
    "2.2.1. atypical lipomatous tumor / well differentiated liposarcoma",
    "2.3.1. dedifferentiated liposarcoma",
    "2.3.2. myxoid liposarcoma",
    "2.3.3. pleomorphic liposarcoma",
    "2.3.4. liposarcoma NOS",
    ### fibroblastic / myofibroblastic tumors
    "3.1.1. nodular fasciitis",
    "3.1.2. proliferative fasciitis",
    "3.1.3. proliferative myositis",
    "3.1.4. myositis ossificans",
    "3.1.5. fibro‐osseous pseudotumor of digits",
    "3.1.6. ischemic fasciitis",
    "3.1.7. elastofibroma",
    "3.1.8. fibrous hamartoma of infancy",
    "3.1.9. fibromatosis colli",
    "3.1.10. juvenile hyaline fibromatosis",
    "3.1.11. inclusion body fibromatosis",
    "3.1.12. fibroma of tendon sheath",
    "3.1.13. desmoplastic fibroblastoma",
    "3.1.14. mammary-type myofibroblastoma",
    "3.1.15. calcifying aponeurotic fibroma",
    "3.1.16. angiomyofibroblastoma",
    "3.1.17. cellular angiofibroma",
    "3.1.18. Nuchal-type fibroma",
    "3.1.19. Gardner fibroma",
    "3.1.20. calcifying fibrous tumor",
    "3.2.1. palmar/plantar fibromatosis",
    "3.2.2. desmoid‐type fibromatosis",
    "3.2.3. lipofibromatosis",
    "3.2.4. giant cell fibroblastoma",
    "3.2.5. dermatofibrosarcoma protuberans",
    "3.2.6. fibrosarcomatous dermatofibrosarcoma protuberans",
    "3.2.7. pigmented dermatofibrosarcoma protuberans",
    "3.2.8. solitary fibrous tumor",
    "3.2.9. solitary fibrous tumor, malignant",
    "3.2.10. inflammatory myofibroblastic sarcoma",
    "3.2.11. low-grade myofibroblastic sarcma",
    "3.2.12. myxoinflammatory fibroblastic sarcoma",
    "3.2.13. infantile fibrosarcoma",
    "3.3.1. adult fibrosarcoma",
    "3.3.2. myxofibrosarcoma",
    "3.3.3. low‐grade fibromyxoid sarcoma (Evans tumor)",
    "3.3.4. sclerosing epithelioid fibrosarcoma",
    ### so called fibrohistiocytic tumors
    "4.1.1. deep benign fibrous histiocytoma",
    "4.2.1. tenosynovial giant cell tumor",
    "4.2.2. plexiform fibrohistiocytic tumor",
    "4.2.3. giant cell tumor of soft tissues",
    ### smooth muscle tumors
    "5.1.1. deep leiomyoma",
    "5.3.1. leiomyosarcoma (excluding skin)",
    ### pericytic (perivascular) tumors
    "6.1.1. angioleiomyoma",
    "6.2.1. glomus tumor and variants",
    "6.2.2. myopericytoma",
    ### skeletal muscle tumors
    "7.1.1. rhabdomyoma",
    "7.3.1. embryonal rhabdomyosarcoma",
    "7.3.2. alveolar rhabdomyosarcoma",
    "7.3.3. pleomorphic rhabdomyosarcoma",
    "7.3.4. spindle cell / sclerosing rhabdomyosarcoma",
    ### vascular tumors of soft tissue
    "8.1.1. hemangioma",
    "8.1.2. epithelioid hemangioma",
    "8.1.3. angiomatosis",
    "8.1.4. lymphangioma",
    "8.2.1. kaposiform hemangioendothelioma",
    "8.2.2. retiform hemangioendothelioma",
    "8.2.3. papillary intralymphatic angioendothelioma",
    "8.2.4. composite hemangioendothelioma",
    "8.2.5. pseudomyogenic (epithelioid sarcoma‐like) hemangioendothelioma",
    "8.2.6. kaposi sarcoma",
    "8.3.1. epithelioid hemangioendothelioma",
    "8.3.2. angiosarcoma of soft tissues",
    ### condro-osseous tumors
    "9.1.1. soft tissue chondroma",
    "9.3.1. extraskeletal mesenchymal chondrosarcoma",
    "9.3.2. extraskeletal osteosarcoma",
    "10.3.3. gist",
    ### nerve sheath tumor
    "11.1.1. schwannoma (including variants)",
    "11.1.2. melanotic schwannoma",
    "11.1.3. neurofibroma (incl. variants)",
    "11.1.4. perineurioma",
    "11.1.5. granular cell tumor",
    "11.1.6. dermal nerve sheath tumor",
    "11.1.7. solitary circumscribed neuroma",
    "11.1.8. ectopic meningioma",
    "11.1.9. nasal glial heterotopia",
    "11.1.10. benign triton tumor",
    "11.1.11. hybrid nerve sheath tumors",
    "11.3.1. malignant peripheral nerve sheath tumor",
    "11.3.2. epithelioid malignant peripheral nerve sheath tumor",
    "11.3.3. malignant triton tumor",
    "11.3.4. malignant granular cell tumor",
    "11.3.5. ectomesenchymoma",
    ### tumors of uncertain differentiation
    "12.1.1. acral fibromyxoma",
    "12.1.2. intramuscular myxoma (incl. variants)",
    "12.1.3. juxtra-articular myxoma",
    "12.1.4. deep (‘aggressive‘) angiomyxoma", ### need to recode because ' is " in Adjumed
    "12.1.5. pleomorphic hyalinizing angietctaic tumor",
    "12.1.6. ectropic hamartomatous thymoma",
    "12.2.1. hemosiderotic fibrolipomatous tumor",
    "12.2.2. atypical fibroxanthoma",
    "12.2.3. angiomatoid fibrous histiocytoma",
    "12.2.4. ossifying fibromyxoid tumor",
    "12.2.5. mixed tumor NOS",
    "12.2.6. myoepithelioma",
    "12.2.7. phosphaturic mesenchymal tumor",
    "12.3.1. synovial sarcoma",
    "12.3.2. epithelioid sarcoma",
    "12.3.3. alveolar soft-part sarcoma",
    "12.3.4. clear cell sarcoma of soft tissue",
    "12.3.5. extraskeletal myxoid chondrosarcoma",
    "12.3.6. extraskeletal ewing sarcoma",
    "12.3.7. desmoplastic small round cell tumor",
    "12.3.8. extra-renal rhabdoid tumor",
    "12.3.9. neoplasms with perivascular epithelioid differentiation (PEComa)",
    "12.3.10. intimal sarcoma",
    ### undifferentiated / unclassified sarcoma
    "13.2.1. dermal undifferentiated sarcoma",
    "13.3.1. undifferentiated / unclassified sarcoma",
    ## chondrogenic tumors
    "15.1.1. osteochondroma",
    "15.1.2. chondroma",
    "15.1.3. osteochondromyxoma",
    "15.1.4. subungual exostosis",
    "15.1.5. bizarre parosteal osteochondromatous proliferation",
    "15.1.6. synovial chondromatosis",
    "15.2.1. chondromyxoid fibroma",
    "15.2.2. atypical chondromatous tumors / chondrosarcoma grade I",
    "15.2.3. chondroblastoma",
    "15.3.1. chondrosarcoma grade II, grade III",
    "15.3.2. dedifferentiated chondrosarcoma",
    "15.3.3. mesenchymal chondrosarcoma",
    "15.3.4. clear cell chondrosarcoma",
    ### osteogenic tumors
    "16.1.1. osteoma",
    "16.1.2. osteoid osteoma",
    "16.2.1. osteoblastoma",
    "16.3.1. low-grade central osteosarcoma",
    "16.3.2. conventional osteosarcoma",
    "16.3.3. teleangiectatic osteosarcoma",
    "16.3.4. small cell osteosarcoma",
    "16.3.5. secondary osteosarcoma",
    "16.3.6. parosteal osteosarcoma",
    "16.3.7. periosteal osteosarcoma",
    "16.3.8. high-grade surface osteosarcoma",
    ### fibrogenic tumors
    "17.2.1. desmoplastic fibroma of bone",
    "17.3.1. fibrosarcoma of bone",
    ### fibrohistiocytic tumors
    "18.1.1. benign fibrous histiocytoma",
    "18.1.2. non‐ossifying fibroma",
    ### ewing sarcoma
    "19.3.1. ewing sarcoma",
    ### osteoclastic giant cell rich tumors
    "21.1.1. giant cell lesion of the small bones",
    "21.2.1. giant cell tumor of bone",
    "21.3.1. malignancy in giant cell tumor of bone",
    ### notochodral tumors
    "22.1.1. benign notochordal tumor",
    "22.3.1. chordoma",
    ### vascular tumors
    "23.1.1. hemangioma",
    "23.2.1. epithelioid hemangioma",
    "23.3.1. epithelioid hemangioendothelioma",
    "23.3.2. angiosarcoma",
    ### myogenic, lipogenic & epithelial tumors
    "24.1.1. leiomyoma of bone",
    "24.1.2. lipoma of bone",
    "24.3.1. leiomyosarcoma of bone",
    "24.3.2. liposarcoma of bone",
    "24.3.3. adamantinoma",
    ### tumors of undefined neoplastic nature
    "25.1.1. simple bone cyst",
    "25.1.2. fibrous dysplasia",
    "25.1.3. osteofibrous dysplasia",
    "25.1.4. chondromesenchymal hamartoma",
    "25.1.5. Rosai-Dorfman disease",
    "25.2.1. aneurysmal bone cyst",
    "25.2.2. Langerhans cell histiocytosis",
    "25.2.3. Erdheim-Chester disease",
    ### undifferentiated high-grade pleomorphic sarcoma
    "26.3.1. undifferentiated high grade pleomorphic sarcoma of bone",
    ### tumor syndromes
    "27.0.1. Beckwith-Wiedemann syndrome",
    "27.0.2. cherubism",
    "27.0.3. enchondromatosis: Ollier",
    "27.0.4. enchondromatosis: Maffucci",
    "27.0.5. Li-Fraumeni syndrome",
    "27.0.6. McCune Albright syndrome",
    "27.0.7. multiple osteochondromas",
    "27.0.8. neurofibromatosis type 1",
    "27.0.9. retinoblastoma syndrome",
    "27.0.10. Rothmund-Thomson syndrome",
    "27.0.11. Werner syndrome",
    ### non-neoplastic / tumor simulator
    "0 non-neoplastic / tumor simulator", # please define in next field!!
    ### metastasis
    "M.1. lung",
    "M.2. breast",
    "M.3. prostate",
    "M.4. kidney",
    "M.5. thyroid",
    "M.6. melanoma",
    "M.7. colon / lower GI",
    "M.8. upper GI",
    "M.9. hepato-biliary-pancreas",
    "M.10. cervix / endometrium",
    "M.11. parotis",
    "M.12. CUP",
    "M.13. other metastasis (please specify in next field)", # reocde & please define in next field!!
    ### lymphoma / myeloma / leukemia
    "BL.0 lymphoma",
    "BL.1 myeloma",
    "BL.2 leukemia", # recode to leukemia
    ### St. post implantation of tumor prosthesis
    "recE.1 type 1: mechanical failure - soft tissue failure",
    "recE.2 type 2: mechanical failure - aseptic loosening",
    "recE.3 type 3: mechanical failure - structural failure",
    "recE.4 type 4: non-mechanical failure - infection",
    "recE.5 type 5: non-mechanical failure - tumor",
    "recE.6 type 6: pediatric failures - all types",
    ### other sequelae of treatment
    "recE.7 other sequelae of treatment" # please define in next field!!
  )
)

drug <- data.frame(
  drug_group = c(rep("cytotoxic drugs", 20),
                 rep("Immunotherapy (Checkpoint-Inhibitors)", 6),
                 rep("Protein Kinase Inhibitors, Tyrosin-Kinase Inhibitors (TKI)", 23),
                 rep("mTOR Inhibitors", 2),
                 rep("PARP Inhibitors", 1),
                 rep("VEGF inhibitors", 2),
                 rep("RANK lingad antibody", 1),
                 rep("EZH2 inhibitors", 1),
                 rep("PI3K inhibitors", 1),
                 rep("MDM2 inhibitors", 1),
                 rep("CDK4/6 inhibitors", 3)
  ),
  drug_name = c("actinomycin D",
                "carboplatin",
                "cisplatin",
                "cyclophosphamid",
                "docetaxel",
                "doxorubicin",
                "liposomal doxorubicin",
                "DTIC (Dacarbazine)",
                "eribulin",
                "etoposid",
                "gemcitabine",
                "ifosfamie",
                "irinotecan",
                "methotrexate",
                "navelbine",
                "paclitaxel",
                "temozolomid",
                "trabectedin",
                "trofosfamid",
                "vincristin",
                #####
                "atezolizumab (PD-L1)",
                "avelumab (PD-L1)",
                "cemiplimab (PD-L1)",
                "durvalumab (PD-L1)",
                "nivolumab (PD-1)",
                "pembrolizumab (PD-1)",
                #####
                "alectinib (ALK)",
                "avapritinib (Ayvakit)",
                "axitinib (VEGFR)",
                "binimetinib (MEK)",
                "cabozantinib (ROS1, MET)",
                "cediranib (VEGFR)",
                "ceritinib (ALK, ROS1)",
                "crizotinib (MET.ROS1)",
                "cobimetinib (MEK)",
                "dasatinib (SRC, BCR-ABL)",
                "encorafenib (BRAF)",
                "erdafitinib (FGFR)",
                "erlotinib (EGFR)",
                "imatinib (cKit, PDGFR a, BCR-ABL)",
                "infigratinib (FGFR)",
                "larotrectinib (NTRK)",
                "lenvatinib (FGFR, PDGFR a, KIT, RET)",
                "pazopanib (VEGFR, PDGFR, KIT)",
                "regorafenib",
                "sorafenib (RAF, c-Kit, FLT, VEGFR, PDGFR)",
                "sunitinib (PDGFR, VEGFR, KIT, FLT3, CSF-1R, RET)",
                "tivantinib (MEK)",
                "vemurafenib (BRAF)",
                #####
                "everolimus",
                "nab sirolimus",
                #####
                "olapatib",
                #####
                "bevacizumab",
                "ramucirumab",
                #####
                "denosumab",
                #####
                "tazemetostat",
                #####
                "alpelisib",
                #####
                "nutlins",
                #####
                "palbociblib",
                "ribociclib",
                "abemaciclib"
  ),
  default = rep(TRUE, 61)
)

hemipelvectomy_name <- data.frame(
  group = c("Not applicable",
            rep("type I", 9),
            rep("type II", 28),
            rep("type III", 5),
            rep("type IV", 18),
            rep("type V", 8)
  ),
  hemipelvectomy_name = c("Not applicable",
                          "resB.12 type I - 1.1. preservation of pelvic ring",
                          "resB.13 type I - 2.1. supra-acetabular: lateral to SIJ",
                          "resB.14 type I - 2.2. supra-acetabular: medial to SIJ; lateral to sacral foramina (through sacral ala)",
                          "resB.14.1 type I - 2.4. supra-acetabular: through sacral foramina",
                          "resB.15 type I - 2.3. supra-acetabular: medial to sacral foramina / midline",
                          "resB.16 type I - 3.1. trans-acetabular: lateral to SIJ",
                          "resB.17 type I - 3.2. trans-acetabular: medial to SIJ; lateral to sacral foramina (through sacral ala)",
                          "resB.17.1 type I - 3.4. trans-acetabular: through sacral foramina",
                          "resB.18 type I - 3.3. trans-acetabular: medial to sacral foramina / midline",
                          "resB.19 type II - 1.1. superior part of Y (incl. parts of ilium)",
                          "resB.20 type II - 1.2. medial part of Y (parts of pubis)",
                          "resB.21 type II - 1.3. posterior / lateral part of Y (incl. parts of ischium)",
                          "resB.22 type II - 2.1. periacetabular (preservation of ilium; ischium; pubis)",
                          "resB.22.1 * A: periacetabular resections: transarticular",
                          "resB.22.2 * B: periacetabular resections: extraarticular with pelvic ring disruption",
                          "resB.22.3 * C: periacetabular resections: extraarticular without pelvic ring disruption (periacetabular resection)",
                          "resB.23 type II - 3.1. lateral to SIJ",
                          "resB.24 type II - 3.2. medial to SIJ - lateral to foramina (through sacral ala)",
                          "resB.24.1 type II - 3.3. medial to foramina / midline",
                          "resB.24.2 * A: acetabulum plus ilium / sacrum: transarticular",
                          "resB.24.3. * B: acetabulum plus ilium / sacrum: extraarticular",
                          "resB24.4 type II - 3.4. through foramina",
                          "resB.25 type II - 4.1. incl. ramus superior / symphysis",
                          "resB.26 type II - 4.2. incl. ischium / tuber ischiadicum",
                          "resB.27 type II - 4.3. complete pubis / ischium (OT through symphysis)",
                          "resB.91 *A: acetabulum plus pubis: transarticular",
                          "resB.92 *B: acetabulum plus pubis: extraarticular",
                          "resB.28.1 type II - 5.1. proximal OT: lateral to SIJ",
                          "resB.28.2 type II - 5.2. proximal OS: medial to SIJ - lateral to foramina (through sacral ala)",
                          "resB.28.3 type II - 5.3. proximal OT: medial to foramina / midline",
                          "resB.28.4 type II - 5.a. distal OT: incl. ramus superior / symphysis",
                          "resB.28.5 type II - 5.b. distal OT: incl. tuber ischiadicum",
                          "resB.28.6 type II - 5.c. distal OT: pubis & ischium",
                          "resB.28.7 type II - 5.4. through foramina",
                          "resB.28 *A: acetabulum plus pubis / ischium and ilium / sacrum: trans-articular",
                          "resB.29 *B: acetabulum plus pubis / ischium and ilium / sacrum: extra-articular with pelvic ring disruption",
                          "resB.30 *C: acetabulum plus pubis / ischium and ilium / sacrum: extra-articular without pelvic ring disruption",
                          "resB.31 type III - 1.1. superior ramus",
                          "resB.32 type III - 1.2. inferior ramus",
                          "resB.33 type III - 1.3. both superior and inferior rami",
                          "resB.38 *A: tuber ischiadicum: preserved",
                          "resB.39 *B: tuber ischiadium: resected",
                          "resB.40 type IV - 1.1. partial; unilateral",
                          "resB.41 type IV - 1.2. complete / bilateral",
                          "resB.41.1 * A: posterior approach only",
                          "resB.41.2. * B: combined anterior & posterior approach",
                          "resB.41.3. * C: plus exenteration",
                          "resB.42 type IV - 2.1. no spino-pelvic dissociation",
                          "resB.43 type IV - 2.2. unilateral spino-pelvic dissociation",
                          "resB.44 type IV - 2.3. bilateral spino-pelvic dissociation",
                          "resB.49.1 * A: posterior approach only",
                          "resB.50.1 * B: combined anterior & posterior approach",
                          "resB.51.1 * C: plus exenteration",
                          "resB.45 type IV - 3.1. complete spino-pelvic dissociation",
                          "resB.46 type IV - 3.2. with parts of lumbar spine",
                          "resB.47 type IV - 3.3. with parts of iliac bone",
                          "resB.48 type IV - 3.4. with parts of lumbar & iliac bones",
                          "resB.49.2 * A: posterior approach only",
                          "resB.50.2 * B: combined anterior & posterior approach",
                          "resB.51.2 * C: plus exenteration",
                          "resB.54 hemipelvectomy type V - 1. trans-acetabular (with dissociation of pelvic ring; excluding hip disarticulation)",
                          "resB.55 hemipelvectomy type V - 2. trans-ilium (extra-articular - incl. supra-acetabular)",
                          "resB.56 hemipelvectomy type V - 3. trans-hemi-sacral incl. hemilumbar without contralateral spinopelvic dissociation",
                          "resB.57 hemipelvectomy type V - 4. trans-hemi-sacral incl. hemilumbar with contralateral spinopelvic dissociation",
                          "resB.58 hemipelvectomy type V - 5. hemicorporectomy",
                          "resB.59 * A: posterior flap",
                          "resB.60 * B: anterior flap",
                          "resB.61 * C: other (please specify in next field)"
  )
)

institution <- data.frame(
  institution_name = c("Ente Ospedaliero Cantonale (EOC)",
                       "GZO Spital Wetzikon",
                       "Kantonsspital Aarau (KSA)",
                       "Kantonsspital Baden (KSB)",
                       "Kantonsspital Frauenfeld (KSF)",
                       "Kantonsspital Graubuenden (KSGR)",
                       "Kantonsspital Muensterlingen (KSM)",
                       "Kantonsspital Schaffhausen (KSSH)",
                       "Kantonsspital Winterthur (KSW)",
                       "Kantonsspital Winterthur (KSW) - Altdorf",
                       "Kantonsspital Winterthur (KSW) - Winterthur",
                       "Kantonsspital Zug (KSZG)",
                       "Kinderspital Zuerich",
                       "Klinik Hirslanden",
                       "KSS - Schwyz",
                       "Luzerner Kantonsspital (LUKS)",
                       "Ostsschweizer Kinderspital (OKS) - Luzern",
                       "Ostsschweizer Kinderspital (OKS) - St. Gallen",
                       "Pathologie Institut Enge",
                       "Stadtspital Waid und Triemli (SWT)",
                       "Universitaets-Kinderspital beider Basel (UKBB)",
                       "Universitaetsspital Basel (USB)",
                       "Universitaetsspital Zuerich (USZ)",
                       "USZ - EOC",
                       "USZ - LUKS"
  )
)

insurance <- data.frame(
  insurance_name = c(
    "Unknown",
    "Assura",
    "Atupri",
    "Concordia",
    "CSS",
    "Helsana",
    "KPT",
    "Mutuel Assurance",
    "Sanitas",
    "Swica",
    "Visana"
  )
)

reconstruction_name <- data.frame(
  group = c("Not applicable",
            "skin- / mesh-graft",
            rep("pedicled tissue transfer", 17),
            rep("free tissue transfer", 5),
            rep("tendon / ligament", 3),
            rep("bone", 22),
            rep("vessel", 6),
            rep("nerve", 4),
            "chest wall",
            rep("abdomen", 6),
            rep("sequelae of primary treatment", 3)
  ),
  sub = c("Not applicable",
          "skin- / mesh-graft",
          rep("muscle flaps", 15),
          rep("perforator flap", 2),
          rep("free tissue transfer", 3),
          rep("perforator flap", 2),
          rep("tendon / ligament", 3),
          rep("bone", 22),
          rep("vessel", 6),
          rep("nerve", 4),
          "chest wall",
          rep("abdominal wall reconstruction", 1),
          rep("Intraabdominal reconstruction", 5),
          rep("sequelae of primary treatment", 3)
  ),
  reconstruction_name = c("Not applicable",
                          ###
                          "recA.1 skin- / mesh-graft",
                          ###
                          "recB.1 rectus abdominis",
                          "recB.15 rectus abdominis (with skin)",
                          "recB.2 gastrocnemius",
                          "recB.25 gastrocnemius (with skin)",
                          "recB.3 latissimus dorsi",
                          "recB.35 latissmus dorsi (with skin)",
                          "recB.4 gracilis",
                          "recB.45 gracilis (with skin)",
                          "recB.5 sartorius",
                          "recB.55 sartorius (with skin)",
                          "recB.6 soleus",
                          "resB.65 soleus (with skin)",
                          "recB.7 serratus",
                          "recB.75 serratus (with skin)",
                          "recB.10 other muscle flap (please specify in next field)",
                          "recB.8 ALT",
                          "recB.9 other (please specify in next field)",
                          ###
                          "recC.1 latissimus dorsi",
                          "recC.2 gracilis",
                          "recC.5 other free rissue transfer (please specify in next field)",
                          "recC.3 ALT",
                          "recC.4 other perforator flap (please specify in next field)",
                          ###
                          "recJ.1 autologous tendon transfer",
                          "recJ.2 allograft tendon reconstruction",
                          "recJ.3 local tendon reconstruction",
                          ###
                          "recD.1 cementation",
                          "recD.2 ORIF (incl. bone ankers; removal of OS material)",
                          "recD.13 pedicle screws / rods / cages",
                          "recD.16 artificial bone substitute (Ca-sulfate etc)",
                          "recD.3 autograft",
                          "recD.4 vascularised fibula autograft (based on fibular artery)",
                          "recD.20 vascularised epiphyseal transfer (based on tibial anterior artery)",
                          "recD.5 non-vascularised fibula autograft",
                          "recD.6 pasteurised autograft",
                          "recD.7 allograft chips",
                          "recD.8 bulk allograft",
                          "recD.9 conventional prosthesis",
                          "recD.10 modular tumor prosthesis",
                          "recD.11 custom-made prosthesis",
                          "recD.12 growing prosthesis",
                          "recD.18 arthrodesis",
                          "recD.15 distraction osteogenesis",
                          "recD.17 cement spacer / pseudoarthrosis / flail joint",
                          "recD.19 Canadell distraction epiphyseolysis",
                          "recD.14 other bone reconstruction (please specify in next field)",
                          "recD.21 pseudarthrosis (intentional)",
                          "recD.22 goretex mesh; Trevira etc",
                          ###
                          "recF.1 artery complete",
                          "recF.2 artery patch",
                          "recF.3 vein complete",
                          "recF.4 vein patch",
                          "recF.5 lympho-venous",
                          "recF.6 other vessel reconstruction (please specify in next field)",
                          ###
                          "recG.1 nerve reconstruction (please specify in next field)",
                          "recG.2 neurotisation / local transfer",
                          "recG.31 neurotisation / local transfer autologous (please specify in next field)",
                          "recG.32 neurotisation / local transfer allograft",
                          ###
                          "recH chest wall reconstruction",
                          ###
                          "recI.1 wall",
                          ###
                          "recI.2 colon anastomosis",
                          "recI.3 stoma",
                          "recI.4 bladder",
                          "recI.5 ureter",
                          "recI.6 other intraabdominal reconstruction (please specify in next field)",
                          ###
                          "recK.1 cement spacer implantation",
                          "recK.2 partial implantation / replacement",
                          "recK.3 complete prosthesis implantation / replacement"
  )
)

resection_name <- data.frame(
  group = c(
    "Not applicable",
    rep("soft tissues", 13),
    rep("bone", 17),
    rep("chest / thorax", 10),
    rep("abdomen", 15),
    rep("sequelae of primary treatment", 11)
  ),
  sub = c(  "Not applicable",
            rep("STS resection", 13),
            ####
            rep("bone resection", 17),
            #rep("internal hemipelvectomy", 60),
            #rep("amputation", 22),
            ####
            rep("chest wall resection", 1),
            rep("open thoracotomy", 7),
            rep("thoraco-endoscopic resection (VATS)", 2),
            ####
            rep("abdominal wall resection", 1),
            rep("abdominal resection", 14),
            ####
            rep("soft tissue revision", 2),
            rep("bone revision", 4),
            rep("St. post tumor prosthesis implantation", 5)

  ),
  resection_name = c("Not applicable",
                     "resA.1 simple",
                     "resA.2 muscle resection",
                     "resA.3 vessel dissection",
                     "resA.4 nerve dissection",
                     "resA.5 periost resection",
                     "resA.6 bone resection",
                     "resA.7 vessel resection",
                     "resA.8 nerve resection",
                     "resA.9 MR-HIFU",
                     "resA.10 tendon resection",
                     "resA.11 ligament resection",
                     "resA.12 resection of funiculus; scrotum; genitals",
                     "resA.13 other STS resection (please specify in next field)", ##
                     ####
                     "resB.1 simple curettage",
                     "resB.2 hemi-cortex resection",
                     "resB.3 complete / whole bone res. (incl. adj. soft tiss.): joint sparing (outside / preservation of joint)",
                     "resB.4 complete / whole bone res. (incl. adj. soft tiss.): transarticular resection (through the joint)",
                     "resB.5 complete / whole bone res. (incl. adj. soft tiss.): extraarticular joint resection",
                     "resB.6 with 3D patient specific cutting guides",
                     "resB.6.1 3D planning",
                     "resB.8 radiofrequency ablation (RFA); cryotherapy; MR-HIFU",
                     "resB.9 resection-replantation (upper extremity)",
                     "resB.10 rotationplasty (lower extremity)",
                     "resB.80 tendon resection",
                     "resB.81 ligament resection",
                     "resB.82 forced epiphyseolysis OT (Canadell technique)",
                     "resB.83 extra-articular scapulo-humeral resection (Tikhoff-Linberg)",
                     "resB.84 biopsy / gain of diagnostic tissue",
                     "resB.85 removal of cement",
                     "resB.86 other bone resection (please specify in next field)", ##
                     ####
                     # "resB.12 type I - 1.1. preservation of pelvic ring",
                     # "resB.13 type I - 2.1. supra-acetabular: lateral to SIJ",
                     # "resB.14 type I - 2.2. supra-acetabular: medial to SIJ, lateral to sacral foramina (through sacral ala)",
                     # "resB.14.1 type I - 2.4. supra-acetabular: through sacral foramina",
                     # "resB.15 type I - 2.3. supra-acetabular: medial to sacral foramina / midline",
                     # "resB.16 type I - 3.1. trans-acetabular: lateral to SIJ",
                     # "resB.17 type I - 3.2. trans-acetabular: medial to SIJ, lateral to sacral foramina (through sacral ala)",
                     # "resB.17.1 type I - 3.4. trans-acetabular: through sacral foramina",
                     # "resB.18 type I - 3.3. trans-acetabular: medial to sacral foramina / midline",
                     # "resB.19 type II - 1.1. superior part of Y (incl. parts of ilium)",
                     # "resB.20 type II - 1.2. medial part of Y (parts of pubis)",
                     # "resB.21 type II - 1.3. posterior / lateral part of Y (incl. parts of ischium)",
                     # "resB.22 type II - 2.1. periacetabular (preservation of ilium, ischium, pubis)",
                     # "resB.22.1 * A: periacetabular resections: transarticular",
                     # "resB.22.2 * B: periacetabular resections: extraarticular with pelvic ring disruption",
                     # "resB.22.3 * C: periacetabular resections: extraarticular without pelvic ring disruption (periacetabular resection)",
                     # "resB.23 type II - 3.1. lateral to SIJ",
                     # "resB.24 type II - 3.2. medial to SIJ - lateral to foramina (through sacral ala)",
                     # "resB.24.1 type II - 3.3. medial to foramina / midline",
                     # "resB.24.2 * A: acetabulum plus ilium / sacrum: transarticular",
                     # "resB.24.3. * B: acetabulum plus ilium / sacrum: extraarticular",
                     # "resB24.4 type II - 3.4. through foramina",
                     # "resB.25 type II - 4.1. incl. ramus superior / symphysis",
                     # "resB.26 type II - 4.2. incl. ischium / tuber ischiadicum",
                     # "resB.27 type II - 4.3. complete pubis / ischium (OT through symphysis)",
                     # "resB.91 *A: acetabulum plus pubis: transarticular",
                     # "resB.92 *B: acetabulum plus pubis: extraarticular",
                     # "resB.28.1 type II - 5.1. proximal OT: lateral to SIJ",
                     # "resB.28.2 type II - 5.2. proximal OS: medial to SIJ - lateral to foramina (through sacral ala)",
                     # "resB.28.3 type II - 5.3. proximal OT: medial to foramina / midline",
                     # "resB.28.4 type II - 5.a. distal OT: incl. ramus superior / symphysis",
                     # "resB.28.5 type II - 5.b. distal OT: incl. tuber ischiadicum",
                     # "resB.28.6 type II - 5.c. distal OT: pubis & ischium",
                     # "resB.28.7 type II - 5.4. through foramina",
                     # "resB.28 *A: acetabulum plus pubis / ischium and ilium / sacrum: trans-articular",
                     # "resB.29 *B: acetabulum plus pubis / ischium and ilium / sacrum: extra-articular with pelvic ring disruption",
                     # "resB.30 *C: acetabulum plus pubis / ischium and ilium / sacrum: extra-articular without pelvic ring disruption",
                     # "resB.31 type III - 1.1. superior ramus",
                     # "resB.32 type III - 1.2. inferior ramus",
                     # "resB.33 type III - 1.3. both superior and inferior rami",
                     # "resB.38 *A: tuber ischiadicum: preserved",
                     # "resB.39 *B: tuber ischiadium: resected",
                     # "resB.40 type IV - 1.1. partial, unilateral",
                     # "resB.41 type IV - 1.2. complete / bilateral",
                     # "resB.41.1 * A: posterior approach only",
                     # "resB.41.2. * B: combined anterior & posterior approach",
                     # "resB.41.3. * C: plus exenteration",
                     # "resB.42 type IV - 2.1. no spino-pelvic dissociation",
                     # "resB.43 type IV - 2.2. unilateral spino-pelvic dissociation",
                     # "resB.44 type IV - 2.3. bilateral spino-pelvic dissociation",
                     # "resB.49.1 * A: posterior approach only",
                     # "resB.50.1 * B: combined anterior & posterior approach",
                     # "resB.51.1 * C: plus exenteration",
                     # "resB.45 type IV - 3.1. complete spino-pelvic dissociation",
                     # "resB.46 type IV - 3.2. with parts of lumbar spine",
                     # "resB.47 type IV - 3.3. with parts of iliac bone",
                     # "resB.48 type IV - 3.4. with parts of lumbar & iliac bones",
                     # "resB.49.2 * A: posterior approach only",
                     # "resB.50.2 * B: combined anterior & posterior approach",
                     # "resB.51.2 * C: plus exenteration",
                     ####
                     # "resB.52 forequarter amputation with chest wall",
                     # "resB.53 forequarter amputation without chest wall",
                     # "resB.54 hemipelvectomy type V - 1. trans-acetabular (with dissociation of pelvic ring; excluding hip disarticulation)",
                     # "resB.55 hemipelvectomy type V - 2. trans-ilium (extra-articular - incl. supra-acetabular)",
                     # "resB.56 hemipelvectomy type V - 3. trans-hemi-sacral incl. hemilumbar without contralateral spinopelvic dissociation",
                     # "resB.57 hemipelvectomy type V - 4. trans-hemi-sacral incl. hemilumbar with contralateral spinopelvic dissociation",
                     # "resB.58 hemipelvectomy type V - 5. hemicorporectomy",
                     # "resB.59 * A: posterior flap",
                     # "resB.60 * B: anterior flap",
                     # "resB.61 * C: other (please specify in next field)",
                     # "resB.62 should joint trans-articular",
                     # "resB.63 humerus",
                     # "resB.64 elbow joint",
                     # "resB.65 forearm",
                     # "resB.66 hand / wrist",
                     # "resB.67 finger",
                     # "resB.68 hip disarticulation",
                     # "resB.69 thigh",
                     # "resB.70 knee joint",
                     # "resB.71 BKA",
                     # "resB.72 foot",
                     # "resB.90 digit",
                     ####
                     "resC.1 chest wall resection",
                     "resC.2 wedge resection",
                     "resC.3 segmental resection",
                     "resC.4 lobectomy",
                     "resC.5 bilobectomy / pneumonectomy",
                     "resC.6 pleuropneumonectomy",
                     "resC.7 thoracic wall resection / ribs",
                     "resC.10 other chest / lung resection (please specify in next field)", ###
                     "resC.8 wedge resection",
                     "resC.9 lobectomy",
                     ####
                     "resD.1 abdominal wall resection",
                     "resD.2 none", ### ????
                     "resD.3 kidney",
                     "resD.4 suprarenal glands",
                     "resD.5 ureter",
                     "resD.6 bladder",
                     "resD.7 colon / rectum",
                     "resD.8 bowel",
                     "resD.9 uterus / ovaries",
                     "resD.10 spleen",
                     "resD.11 liver",
                     "resD.12 pancreas",
                     "resD.13 gall bladder",
                     "resD.14 aorta / cava",
                     "resD.15 other abdominal resection (please specify in next field)",
                     ####
                     "resE.5 infection",
                     "resE.7 wound healing failure (incl. hematoma)",
                     "resE.8 infection",
                     "resE.9 osteosynthesis failure",
                     "resE.10 fracture",
                     "resE.12 pseudoarthrosis",
                     "resE.1 debridement",
                     "resE.2 inlay change",
                     "resE.3 partial removal of prosthesis",
                     "resE.4 complete removal of prosthesis",
                     "resE.11 other (please specify in next field)"
  )
)

weekdays <- unlist(
  lapply(X = seq(from=as.Date("2000-01-01"), to = as.Date("2030-01-01"), by = 1), FUN = function(x){weekdays(x)}))

dates <- seq(from=as.Date("2000-01-01"), to = as.Date("2030-01-01"), by = 1)

dats <- data.frame(weekdays = weekdays,
                   dates = dates)

sarcoma_board_date <- data.frame(sb_date = dats$dates[dats$weekdays == "Tuesday"])

toxicity_name <- data.frame(
  toxicity_name = c(
    "unknown",
    "no acute toxicity",
    "fever",
    "neutropenia",
    "rash",
    "polyneuropathy",
    "cardiotoxicity",
    "acute QT-prolongation",
    "hepatotoxicity",
    "encephalopathy",
    "renal insufficiency",
    "mucositis",
    "fatigue",
    "hyperglycemia",
    "thrombocytopenia",
    "endocrine",
    "alopecia",
    "myelotoxicity",
    "infertility",
    "hand foot syndrome",
    "other acute toxicity",
    "no chronic toxicity",
    "persistent neutropenia",
    "persistent thrombocytopenia",
    "persistent polyneuropathy",
    "chronic renal insufficiency",
    "permanent endocrine deficits",
    "irreversible or chronic cardiotoxicity",
    "chronic QT-prolongation",
    "chronic hepatopathia",
    "dyslipidemia",
    "persistent skin damage",
    "skin disorders (incl. hair)",
    "chronic fatigue syndrome",
    "hypertension",
    "hearling loss",
    "MDS",
    "mood disorder",
    "cognitive disorder",
    "irAE",
    "second cancer",
    "fertility",
    "irreversible alopecia",
    "other chronic toxicity"
  ),
  toxicity_type = c("unknown",
                    rep("acute", 20),
                    rep("chronic", 23)),
  # acute or chronic
  default = rep(TRUE, 44)
)

user <- data.frame(
  user_id = c(0 ,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
              18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
              34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
              50, 51, 52, 53, 54),
  last_name = c("Unknown", "Aebi", "Anthonipillai", "Baumert", "Bode", "Bode", "Brodmann",
                "Blum", "Campanna", "Collen", "Ehrler", "Elyes", "Falkowski",
                "Feusi", "Finkenstaedt", "Franchi", "Frei", "Fuchs", "Grieder",
                "Heesen", "Hoeng", "Kelaney", "Kestenholz", "Klass", "Kopf",
                "Kronberger", "Kurnzle", "Mattmann", "Meier", "Michelitsch",
                "Mosku", "Najafi", "Niederberger", "Niggli", "Odermatt", "Pesce",
                "Plecko", "Rajmon", "Schaerer", "Schelling", "Schmid", "Schneider",
                "Spataro", "Studer", "Tavella", "Theus-Steinemann", "Treumann",
                "Vanoudenaarde", "Vishaj", "Vogetseder", "Went", "Winterhalder",
                "Yogaratnam", "Zachariah", "Zwahlen"),
  first_name = c("Unknown", "Stefan", "Jenestin", "Brigitta", "Peter", "Beata", "Stefan",
                 "Veronika", "Benedetta", "Timothy", "Jelia", "Maria", "Anna",
                 "Dario", "Tim", "Alberto", "Annika", "Bruno", "Felix", "Philip",
                 "Laura", "Mohamed", "Peter", "Natali Desiree", "Barbara", "Leo",
                 "Sergio", "Alexander", "Beatrice", "Christian", "Nasian", "Arash",
                 "Philipp", "Cedric", "Manfred", "Gianfranco Angelo", "Drago",
                 "Eva", "Markus", "Georg", "Sandra", "Paul Magnus", "Vito", "Gabriela",
                 "Lorenzo", "Carlo", "Thomas", "Kim", "Jehona", "Alexander", "Philip",
                 "Ralph", "Shaijeni", "Ralph", "Daniel"),
  email = c("Unknown", "stefan.aebi@luks.ch", "jenestin.anthonipillai@student.unisg.ch",
            "brigitta.baumert@ksgr.ch", "peter.bode@ksw.ch", "beata.bode@patho.ch",
            "stefan.brodmann@ksw.ch", "veronika.blum@luks.ch", "benedetta.campanna@luks.ch",
            "timothy.collen@luks.ch", "jeliaehrler@gmail.com", "maria.elyes@uzh.ch",
            "anna.falkowski@ksw.ch", "dario.feusi@uzh.ch", "tim.finkenstaedt@ksw.ch",
            "alberto.franchi@ksw.ch", "annika.frei@ksw.ch", "bruno.fuchs@ksw.ch",
            "felix.grieder@ksw.ch", "philip.heesen@uzh.ch", "laura.hoeng@luks.ch",
            "kelaney.m@med.asu.edu.eg", "peter.kestenholz@luks.ch", "nataliedesiree.klass@ksgr.ch",
            "Barbara.Kopf@eoc.ch", "leo.kronberger@luks.ch", "sergio.kuenzle@gmail.com",
            "alexander.mattmann@luks.ch", "beatrice.meier@ksw.ch", "christian.michelitsch@ksgr.ch",
            "nmosku45@gmail.com", "arash.najafi@ksw.ch", "philipp.niederberger@spital-nidwalden.ch",
            "cedric.niggli@swissonline.ch", "Manfred.Odermatt@stadtspital.ch",
            "gianfrancoangelo.pesce@eoc.ch", "www.plecko@gmail.com", "eva.rajmon@gmail.com",
            "markus@schaerer-family.ch", "Georg.schelling@ksw.ch", "sandra.schmid.4@luks.ch",
            "sekretariat.professor-schneider@hin.ch", "vito.spataro@hin.ch",
            "gabriela.studer@luks.ch", "lorenzo.tavella@eoc.ch", "carlotheus@gmail.com",
            "thomas.treumann@luks.ch", "kim.vanoudenaarde@luks.ch", "jehona.vishaj@luks.ch",
            "alexander.vogetseder@luks.ch", "philip.went@mac.com", "ralph.winterhalder@luks.ch",
            "shaijeni01@hotmail.com", "ralph.zachariah@ksw.ch", "daniel.zwahlen@ksw.ch"),
  institution = c("Unknown", "LUKS", "UNISG", "KSGR", "KSW", "PIE", "KSW", "LUKS", "LUKS",
                  "LUKS", "UniLU", "UniLU", "KSW", "UZH", "KSW", "KSW", "KSW",
                  "LUKS", "KSW", "UZH", "LUKS", "UniCairo", "LUKS", "KSGR", "EOC",
                  "UZH", "UniLU", "LUKS", "KSW", "KSGR", "UniLU", "KSW", "LUKS",
                  "SSN", "SWT", "EOC", "ETH", "UniLU", "UniLU", "LUKS", "LUKS",
                  "Hirslanden", "EOC", "LUKS", "EOC", "LUKS", "LUKS", "LUKS", "LUKS",
                  "LUKS", "KSGR", "LUKS", "UniLU", "KSW", "KSW"),
  discipline = c("Unknown", "medical oncology", "student", "radiation oncology", "pathology",
                 "pathology", "radiation oncology", "medical oncology", "radiation oncology",
                 "radiation oncology", "data manager", "MD student", "radiology",
                 "MD student", "radiology", "reconstructive surgery", "data manager",
                 "sarcoma surgery", "visceral surgery", "data scientist", "radiation oncology",
                 "medical oncology", "chest surgery", "radiation oncology", "medical oncology",
                 "MD student", "data manager", "psychooncology", "assistant",
                 "visceral surgery", "PhD student", "interventional radiology",
                 "medical oncology", "research associate", "visceral surgery",
                 "radiation oncology", "research associate", "MD student", "MD student",
                 "orthopedic oncology", "medical oncology", "visceral surgery",
                 "medical oncology", "radiation oncology", "medical oncology",
                 "orthopedic oncology", "radiology", "radiology", "assistant",
                 "pathology", "pathology", "medical oncology", "MD student", "medical oncology",
                 "radiation oncology"))

user$access = rep(1, nrow(user))
user$reference_from = rep(NA, nrow(user))
user$reference_to = rep(NA, nrow(user))


user$reference_from[user$first_name=="Beata" & user$last_name == "Bode"] <- as.character("2000-01-01")

user$institution <- dplyr:: recode(user$institution,
                                   "EOC" = "Universitaetsspital Zuerich (USZ)",
                                   "Hirslanden" = "Klinik Hirslanden",
                                   "KSW" = "Kantonsspital Winterthur (KSW)",
                                   "LUKS" = "Luzerner Kantonsspital (LUKS)",
                                   "PIE" = "Pathoinstitut Enge",
                                   "SSN" = "Swiss Sarcoma Network (SSN)",
                                   "UniLU" = "Universitaet Luzern",
                                   "UNISG" = "Universitaet St. Gallen",
                                   "UZH" = "Universitaet Zuerich")

save(amputation_name, anatomic_region, diagnosis_who,
     drug, hemipelvectomy_name, institution,
     insurance, reconstruction_name, resection_name,
     sarcoma_board_date, toxicity_name, user,
     file = here::here("inst/extdata/tables.RData"))
